# Generated by Django 3.0.4 on 2020-03-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200313_2329'),
        ('empresa', '0003_auto_20200313_2316'),
        ('servicios', '0002_auto_20200313_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='Empresa',
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Colaborador'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_de_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.CategoriaServicio'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
