# Generated by Django 3.0.4 on 2020-03-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=35)),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
                ('direccion', models.CharField(default='Dirección del cliente', max_length=200)),
                ('sexo', models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')], default=1)),
                ('telefono', models.CharField(default='Teléfono del cliente', max_length=9)),
                ('correo', models.EmailField(default='example@email.com', max_length=255)),
                ('cedula', models.CharField(default='1.111.111-1', max_length=15)),
                ('observaciones', models.CharField(default='', max_length=1000)),
                ('Empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa')),
            ],
        ),
    ]
