# Generated by Django 3.0.4 on 2020-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
