# Generated by Django 3.0.4 on 2020-03-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200310_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='rut de la empresa', max_length=25)),
                ('razon_social', models.CharField(default='razón social de la empresa', max_length=50)),
                ('direccion', models.CharField(default='Dirección de la empresa', max_length=200)),
                ('telefono', models.CharField(default='Teléfono de la empresa', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='1.111.111-1', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Empresa'),
        ),
    ]
