# Generated by Django 2.2.6 on 2020-03-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposervicio', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellido', models.CharField(max_length=35)),
                ('sexo', models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')], default=1)),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
            ],
        ),
    ]
