# Generated by Django 3.0.4 on 2020-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Nombre',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
