# Generated by Django 3.0.4 on 2020-03-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20200330_1911'),
        ('empresa', '0002_auto_20200328_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
