# Generated by Django 3.0.4 on 2020-03-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_delete_categoriaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='rut de la empresa', max_length=25)),
                ('razon_social', models.CharField(default='razón social de la empresa', max_length=50)),
                ('direccion', models.CharField(default='Dirección de la empresa', max_length=200)),
                ('telefono', models.CharField(default='Teléfono de la empresa', max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='Apellido',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='Observaciones',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cedula',
            field=models.CharField(default='1.111.111-1', max_length=15),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='correo',
            field=models.EmailField(default='example@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='direccion',
            field=models.CharField(default='Dirección del cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(default='Teléfono del cliente', max_length=9),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='Nombre',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa'),
        ),
    ]
