# Generated by Django 2.2.6 on 2020-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20200323_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cedula',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='correo',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
